# Generated by Django 3.1.7 on 2021-04-07 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210407_1738'),
        ('comment', '0002_auto_20210322_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='advert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='core.post'),
        ),
    ]
