# Generated by Django 3.1.7 on 2021-04-17 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20210407_1738'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='advert',
            new_name='post',
        ),
    ]
