# Generated by Django 3.1.7 on 2021-03-22 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratings',
            options={'verbose_name_plural': 'Ratings'},
        ),
    ]
