# Generated by Django 3.1.7 on 2021-04-07 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210328_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('text', models.TextField(max_length=5000)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='uploads/')),
            ],
            options={
                'verbose_name_plural': 'Posts',
            },
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='author',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='category',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='subcategory',
        ),
    ]
