# Generated by Django 3.1.7 on 2021-04-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_post_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='allow_comment',
            field=models.BooleanField(default=False),
        ),
    ]
